### ISSUE TITLE
How do you determine if commands "make it" to the machine

### ISSUE THREAD

**Issue by NicolaiMogensen** [ryanalden/esphome-jura-component#7]
We have a Jura Giga X9C, and we can talk with the ESP board just fine, just nothing happens with the coffee machine. We can see in ESPHome that it receives the commands from HA, but nothing seems to happen with the coffee machine. So the board is getting power, but how do we know that the codes we are sending are interacting with the machine?

Also how do you figure out the correct signals for your specific model?

**Comment by ryanalden** [comment]
Hi, you can monitor communication with [ESPhome's UART debugging commands](https://esphome.io/components/uart.html#debugging).

One caveat is that newer machines seem to respond differently than the older models, and if a command is unrecognized you won't see any response whatsoever.  I have had success with the "TY:" command on both older and newer machines, so that might be a good command to use while troubleshooting communications.

Also you can swap TX/RX pins if you continue to have no response, because that can easily be the issue.

Commands for your particular model are found through experimentation, unless you are lucky enough to find that someone else has determined them already. Good luck and please share any codes you find :)

**Comment by NicolaiMogensen** [comment]
Hi @ryanalden thanks for the response. We found the correct pin-out diagram for our board, and added GPIO4 and GPIO5 for the TX and RX pins, and now we can atleast send commands. 

We found that for our model, the RX commands for retrieving coffees made is not correct sadly. But we found that we could simulate the commands of the "wheel" by sending the FA:0X commands. So now we can atleast make coffee. We found in another repository a remark about the correspondance over the RX might be encrypted on newer machines, something about a 80bit handshake message, which might indicate a DES encryption key. But tbh i just don't know, and do not have the skillset to explore this further. Trying to read out memory that makes any sort of sense seems to be beyond the scope of my knowledge.

**Comment by NicolaiMogensen** [comment]
Also thanks alot for the python script, it makes generating commands a lot easier.

**Comment by NicolaiMogensen** [comment]
For reference, this page was helpfulp:

https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/
![image](https://user-images.githubusercontent.com/11227437/167787876-65c83268-f174-48f6-8b54-53decdd20371.png)

And this repo for commands:
https://github.com/COM8/esp32-jura
